version: '3'
services:
  api:
    restart: always
    build: ./api
    container_name: api
    ports:
      - "5555:5000"
    depends_on:
      - mysql
  frontend:
    restart: always
    build: ./frontend
    container_name: api
    ports:
      - "8954:8954"
    depends_on:
      - api
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=time_db
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - api

    